### ISSUE TITLE
Issue when using this mod and better builders wand mod

### ISSUE THREAD

**Issue by Mongole** [longbowrocks/ExplorersDepot#1]
so with this mod active and trying to use a better builders wand to place blocks, as you try to use a BBW wand it throws a error pointed to exdepot and causes the builders wand to only place one block instead of all the highlighted blocks (most of the time placing it invisible until right clicked on)
using exdepot 1.0.1 for 1.12.2, BBW 0.11.1 and forge 14.23.3.2702
[error report.txt](https://github.com/longbowrocks/ExplorersDepot/files/2041813/error.report.txt)

**Comment by longbowrocks** [comment]
I remember thinking that function was rock solid when I first put it together. Now that I'm looking back, I don't know why I thought that. XD

I took a look and I think the issue is pretty clear. I'll try to get a fix in before I leave today. Failing that, it should be up tomorrow.

**Comment by longbowrocks** [comment]
The updated files are up for review on curse. They should get approved soon.
