### ISSUE TITLE
[REQ] Compatibility

### ISSUE THREAD

**Issue by ExcitedName** [longbowrocks/ExplorersDepot#2]
I'm not sure whose side to make the request so I am submitting it to all. Compatibility with [Nether Chest](https://minecraft.curseforge.com/projects/nether-chest?gameCategorySlug=mc-mods&projectID=268888)

**Comment by longbowrocks** [comment]
You found the right place.

At a glance it looks like that mod should work if you turn on the force compatibility option in Explorer's Depot. Did that not work?

**Comment by ExcitedName** [comment]
Lol, I have made the habbit of checking configs before I launch a world. I even noticed that option and thought, ooooh that will be helpful. Then completely spaced it while testing yours and others mods. I took the time to test compatibility with some other mods as well. Here are the results of my tests. Some of my data may not seem relevant, like the hopper pipe from Faucets and Filters, but I just wanted to be thorough in case you found the information useful. 

Minecraft: 1.12.2
Forge: 14.23.5.2768
Explorer's Depot: 1.12.2-1.0.2

COMPATIBLE MODS
-CraftingAutomat-1.0.5
-Hopperducts-1.12-1.5

MOD CONFLICTS

NETHER CHEST-1.1.1:
[CONFIG SETTINGS: Force Compatibility=true, Pickup Keeps Config=true, Storage Range: 10]
-Pencil button shows up but the behavior is the same as that of the current minecarts. Allows the player to set the configuration, but when the inventory is closed after hitting the save button the filter is cleared.
[CONSOLE]
-Getting these every time I save the configuration.
[22:43:47] [Netty Server IO #5/ERROR] [exdepot]: StorageConfig was never added to netherchest.common.tileentity.TileEntityNetherChest@13accc8b for some reason.
[22:43:49] [Server thread/ERROR] [exdepot]: Why doesn't netherchest.common.tileentity.TileEntityNetherChest@13accc8b have a storageConfig?

[LAPIS STAYS IN ENCHANTING TABLE](https://minecraft.curseforge.com/projects/lapis-stays-in-the-enchanting-table?gameCategorySlug=mc-mods&projectID=263905)-1.1.2: 
[CONFIG SETTINGS: Force Compatibility=true, Pickup Keeps Config=true, Storage Range: 10]
-Pencil button shows up but the behavior is the same as that of the current minecarts. Allows the player to set the configuration, but when the inventory is closed after hitting the save button the filter is cleared.
-Very rarely the gui flickers and shows the pencil button. You can tell that Explorer's depot is trying to force compatibility but being overridden by Lapis Stays
-Since you said ender chest are tricky then I can understand not adding compatibility to the ender enchanting table.

[PRIMAL CHESTS](https://minecraft.curseforge.com/projects/primalchests)-1.0.3:
[CONFIG SETTINGS: Force Compatibility=true, Pickup Keeps Config=true, Storage Range: 10]
-Pencil button shows up but the behavior is the same as that of the current minecarts. Allows the player to set the configuration, but when the inventory is closed after hitting the save button the filter is cleared.
[CONSOLE]
RED - [21:10:31] [Netty Server IO #1/ERROR] [exdepot]: StorageConfig was never added to com.blamejared.primalchests.tileentities.TileEntityPrimalChestAdvanced@755139df for some reason.
RED - [21:10:35] [Server thread/ERROR] [exdepot]: Why doesn't com.blamejared.primalchests.tileentities.TileEntityPrimalChestAdvanced@755139df have a storageConfig?

[KILN](https://minecraft.curseforge.com/projects/kiln?gameCategorySlug=mc-mods&projectID=316650)-1.0:
-Semi compatible. Same behavior as vanilla furnace. Pretty much block that is similar to the furnace inventory.

[ENDERFUGE](https://minecraft.curseforge.com/projects/enderfuge?gameCategorySlug=mc-mods&projectID=264938)-1.4.11:
-Pencil button shows up but the behavior is the same as that of the current minecarts. Allows the player to set the configuration, but when the inventory is closed after hitting the save button the filter is cleared.
[CONSOLE]
[22:06:42] [Netty Server IO #5/ERROR] [exdepot]: StorageConfig requested for com.themastergeneral.enderfuge.server.container.ContainerEnderfuge@e85e50f, which can't have StorageConfig.

[GIACOMO'S BOOKSHELF](https://minecraft.curseforge.com/projects/giacomos-bookshelf?gameCategorySlug=mc-mods&projectID=260373)-1.0:
-Pencil button shows up but the behavior is the same as that of the current minecarts. Allows the player to set the configuration, but when the inventory is closed after hitting the save button the filter is cleared.
[CONSOLE]
-Getting these every time I save the configuration.
[22:11:10] [Netty Server IO #5/ERROR] [exdepot]: StorageConfig requested for com.polipo.bookshelf.inventory.ContainerBookShelf@3255ebe5, which can't have StorageConfig.

[FAUCETS AND FILTERS](https://minecraft.curseforge.com/projects/faucets-and-filters)-1.0.2:
-Pencil button shows up but the behavior is the same as that of the current minecarts. Allows the player to set the configuration, but when the inventory is closed after hitting the save button the filter is cleared.

[VANILLA AUTOMATION](t)-1.12.2-1.5.5:
-Works with the Filter and XP Hoppers
-Does not work with the block placer

[WHOPPER](https://minecraft.curseforge.com/projects/whopper)-1.0.2:
-Pencil button shows up but the behavior is the same as that of the current minecarts. Allows the player to set the configuration, but when the inventory is closed after hitting the save button the filter is cleared.

[LAZY LAZULI'S PIPES](https://minecraft.curseforge.com/projects/lazy-lazulis-pipes)-2.0.1:
-Pencil button shows up but the behavior is the same as that of the current minecarts. Allows the player to set the configuration, but when the inventory is closed after hitting the save button the filter is cleared.
-Pencil button outside gui

[UPPERS](https://minecraft.curseforge.com/projects/uppers)-0.0.6:
-Works when Force Compatibility=true
-When Force COmpatibility=false the button shows up but the behavior is the same as that of the current minecarts. Allows the player to set the configuration, but when the inventory is closed after hitting the save button the filter is cleared.

[STEVE'S MACHINES OVERHAUL](https://minecraft.curseforge.com/projects/steves-machine-overhaul)-1.2.8:
-Crashes upon enter text in the search bar. [REPORT](https://pastebin.com/tpfuAYtT)

**Comment by longbowrocks** [comment]
Wow thanks for all this! forceCompatibility would naturally be pretty janky due to the way it works, but it sounds like I could make it work a lot better with some more polish. I'd prefer to start with these issues before working out the features you mentioned.

I've been busy lately so if I don't get to this on Sunday or next weekend it may be a while.

**Comment by ExcitedName** [comment]
You're very welcome. To be honest I find myself actually playing less Minecraft and more testing and such of peoples mods, lol. Eventually I will get back into coding and MAYBE release something. I haven't coded since 1.7.10 and I know A LOT has changed. Take your time, the mod works well enough to use it at the moment. And at least now I know all the bugs to avoid for the time being, lol. I can understand wanting to finish the polishing before moving on. That can get crazy overwhelming, fast. Happy coding. :-)

**Comment by longbowrocks** [comment]
I finally came back to this after so long.
I fixed all the above weird half-working cases, but most of them still aren't directly supported because the mod authors didn't use the Forge API correctly. I recommend using hoppers for these cases.
Now you use a wand to configure chests instead of adding a button to the UI.
Here's the resulting compatibility:
* Enderfuge 1.11 NO, 1.12 NO
* Faucets and Filters 1.11 NO, 1.12 NO
* Giacomo's Bookshelf 1.11 NO, 1.12 NO
* Lapis Stays in Enchanting Table: enchanting tables override rightclick behaviour. I'll need to look into this.
* Lazy Lazuli's Pipes 1.11 NO, 1.12 NO
* Nether Chest 1.11 NO, 1.12 YES
* Primal Chests 1.12 YES
* Steve's Machines Overhaul: Crashes on load because it can't find FarmlandTrampleEvent class. Bad forge version? Maybe I'll get to it but this doesn't look like my problem.
* Uppers 1.12 YES
* Vanilla Automation 1.11 YES, 1.12 YES
* Whopper 1.12 YES

**Comment by longbowrocks** [comment]
I'll close this as soon as I finish the other changes I'm working on and upload the new version to curseforge.

**Comment by ExcitedName** [comment]
Thanks for all of the work. I haven't been on JAVA in some time now. Been checking out this Bedrock version. Going to be getting back to JAVA soon. I'll take a look at it when I get back on that modpack.

**Comment by longbowrocks** [comment]
I committed the fixes, but haven't uploaded a new version yet.
I found some other aspects of the mod that I wanted to improve before uploading a new version.
